### ISSUE TITLE
Dependency conflict while installation

### ISSUE THREAD

**Issue by nik1806** [JdeRobot/DeepLearningStudio#45]
I am following instructions to install 'requirement.txt' in the virtualenv. I encounter the following error message:

```
ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 18), -r requirements.txt (line 37), -r requirements.txt (line 7), -r requirements.txt (line 9) and six==1.16.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested six==1.16.0
    absl-py 0.12.0 depends on six
    google-auth 1.30.1 depends on six>=1.9.0
    grpcio 1.38.0 depends on six>=1.5.2
    protobuf 3.17.1 depends on six>=1.9
    tensorflow-gpu 2.4.1 depends on six~=1.15.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

Executing the following lines will recreate the error. 
```
mkvitualenv dlstudio --python=python3
python3 -m pip install -r requirment.txt
```

The dependency conflict occurs for three libraries - `grpcio`,  `typing-extensions`, and `six`.

**Comment by nik1806** [comment]
One solution is to remove the libraries from `requirement.txt` and let the pip to solve the dependency conflict itself.

Also, we can use the opportunity to upgrade the python version to the latest 3.8 or 3.9 and solve the conflict together.

@sergiopaniego , please suggest how to proceed further and I will implement the solultion.

**Comment by sergiopaniego** [comment]
I suggest upgrading to the latest Python version `3.10` (https://www.python.org/downloads/). 
Regarding the package dependencies, I would suggest letting pip resolve the matching versions by removing the version number on your personal computer. Then, when this process is finished, set back in the requirements.txt the versions that pip has installed.

We have requirements.txt with fixed versions so everyone that installs the repo works with the same dependencies since problems can appear if we work with different packages version and fixing these problems can be more challenging to reproduce.
